// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1olJSr2m4foQC8SFLJL3l74w_9nSYbSo',
    appId: '1:1068825609126:web:8e395ba4c377578fe28567',
    messagingSenderId: '1068825609126',
    projectId: 'fir-flutter-codelab-59282',
    authDomain: 'fir-flutter-codelab-59282.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-59282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgx1BAZfCv05M9Wr5vx6f04FH8YlGxGY4',
    appId: '1:1068825609126:android:321c699f938ccccfe28567',
    messagingSenderId: '1068825609126',
    projectId: 'fir-flutter-codelab-59282',
    storageBucket: 'fir-flutter-codelab-59282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHc29M9RwsW3Ob5WQdB218-6uWJeRcYk',
    appId: '1:1068825609126:ios:f3d682e6e9cc79e4e28567',
    messagingSenderId: '1068825609126',
    projectId: 'fir-flutter-codelab-59282',
    storageBucket: 'fir-flutter-codelab-59282.appspot.com',
    iosClientId: '1068825609126-6mfv81rdhc18j4a1snm6at8gumbdbm21.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasej',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHc29M9RwsW3Ob5WQdB218-6uWJeRcYk',
    appId: '1:1068825609126:ios:f3d682e6e9cc79e4e28567',
    messagingSenderId: '1068825609126',
    projectId: 'fir-flutter-codelab-59282',
    storageBucket: 'fir-flutter-codelab-59282.appspot.com',
    iosClientId: '1068825609126-6mfv81rdhc18j4a1snm6at8gumbdbm21.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasej',
  );
}
